[package]
name = "api-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mile39 = { path = "../../mile39" }
serde_json = "1.0"

