// This file is generated by rust-protobuf 3.0.3. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proto/config.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_3;

#[derive(PartialEq,Clone,Default,Debug,::serde::Serialize,::serde::Deserialize)]
// @@protoc_insertion_point(message:icecondor.Config)
pub struct Config {
    // message fields
    // @@protoc_insertion_point(field:icecondor.Config.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Config.date)
    pub date: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Config.received_at)
    pub received_at: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Config.user_id)
    pub user_id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Config.device_id)
    pub device_id: ::std::string::String,
    /// "source":"GPS: false Cell:false Wifi:true"
    // @@protoc_insertion_point(field:icecondor.Config.source)
    pub source: ::std::string::String,
    /// ,"frequency":"10"}
    // @@protoc_insertion_point(field:icecondor.Config.recording_frequency)
    pub recording_frequency: i32,
    /// "recording":"on" / "off"
    // @@protoc_insertion_point(field:icecondor.Config.recording)
    pub recording: bool,
    // special fields
#[serde(skip)]
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Config {
    fn default() -> &'a Config {
        <Config as ::protobuf::Message>::default_instance()
    }
}

impl Config {
    pub fn new() -> Config {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &Config| { &m.id },
            |m: &mut Config| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "date",
            |m: &Config| { &m.date },
            |m: &mut Config| { &mut m.date },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "received_at",
            |m: &Config| { &m.received_at },
            |m: &mut Config| { &mut m.received_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "user_id",
            |m: &Config| { &m.user_id },
            |m: &mut Config| { &mut m.user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device_id",
            |m: &Config| { &m.device_id },
            |m: &mut Config| { &mut m.device_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "source",
            |m: &Config| { &m.source },
            |m: &mut Config| { &mut m.source },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "recording_frequency",
            |m: &Config| { &m.recording_frequency },
            |m: &mut Config| { &mut m.recording_frequency },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "recording",
            |m: &Config| { &m.recording },
            |m: &mut Config| { &mut m.recording },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Config>(
            "Config",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Config {
    const NAME: &'static str = "Config";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.id = is.read_string()?;
                },
                18 => {
                    self.date = is.read_string()?;
                },
                26 => {
                    self.received_at = is.read_string()?;
                },
                34 => {
                    self.user_id = is.read_string()?;
                },
                42 => {
                    self.device_id = is.read_string()?;
                },
                50 => {
                    self.source = is.read_string()?;
                },
                56 => {
                    self.recording_frequency = is.read_int32()?;
                },
                64 => {
                    self.recording = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.date.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.date);
        }
        if !self.received_at.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.received_at);
        }
        if !self.user_id.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.user_id);
        }
        if !self.device_id.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.device_id);
        }
        if !self.source.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.source);
        }
        if self.recording_frequency != 0 {
            my_size += ::protobuf::rt::int32_size(7, self.recording_frequency);
        }
        if self.recording != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.date.is_empty() {
            os.write_string(2, &self.date)?;
        }
        if !self.received_at.is_empty() {
            os.write_string(3, &self.received_at)?;
        }
        if !self.user_id.is_empty() {
            os.write_string(4, &self.user_id)?;
        }
        if !self.device_id.is_empty() {
            os.write_string(5, &self.device_id)?;
        }
        if !self.source.is_empty() {
            os.write_string(6, &self.source)?;
        }
        if self.recording_frequency != 0 {
            os.write_int32(7, self.recording_frequency)?;
        }
        if self.recording != false {
            os.write_bool(8, self.recording)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Config {
        Config::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.date.clear();
        self.received_at.clear();
        self.user_id.clear();
        self.device_id.clear();
        self.source.clear();
        self.recording_frequency = 0;
        self.recording = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Config {
        static instance: Config = Config {
            id: ::std::string::String::new(),
            date: ::std::string::String::new(),
            received_at: ::std::string::String::new(),
            user_id: ::std::string::String::new(),
            device_id: ::std::string::String::new(),
            source: ::std::string::String::new(),
            recording_frequency: 0,
            recording: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Config {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Config").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Config {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Config {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x12proto/config.proto\x12\ticecondor\"\xea\x01\n\x06Config\x12\x0e\n\
    \x02id\x18\x01\x20\x01(\tR\x02id\x12\x12\n\x04date\x18\x02\x20\x01(\tR\
    \x04date\x12\x1f\n\x0breceived_at\x18\x03\x20\x01(\tR\nreceivedAt\x12\
    \x17\n\x07user_id\x18\x04\x20\x01(\tR\x06userId\x12\x1b\n\tdevice_id\x18\
    \x05\x20\x01(\tR\x08deviceId\x12\x16\n\x06source\x18\x06\x20\x01(\tR\x06\
    source\x12/\n\x13recording_frequency\x18\x07\x20\x01(\x05R\x12recordingF\
    requency\x12\x1c\n\trecording\x18\x08\x20\x01(\x08R\trecordingJ\xc9\x04\
    \n\x06\x12\x04\0\0\x10\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\
    \x02\x12\x03\x01\0\x12\n\n\n\x02\x04\0\x12\x04\x03\0\x10\x01\n\n\n\x03\
    \x04\0\x01\x12\x03\x03\x08\x0e\n\x0b\n\x04\x04\0\x02\0\x12\x03\x04\x02\
    \x10\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x04\x02\x08\n\x0c\n\x05\x04\0\
    \x02\0\x01\x12\x03\x04\t\x0b\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x04\x0e\
    \x0f\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x05\x02\x12\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03\x05\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x05\t\
    \r\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x05\x10\x11\n\x0b\n\x04\x04\0\
    \x02\x02\x12\x03\x06\x02\x19\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x06\
    \x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x06\t\x14\n\x0c\n\x05\x04\
    \0\x02\x02\x03\x12\x03\x06\x17\x18\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x07\
    \x02\x15\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x07\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x03\x01\x12\x03\x07\t\x10\n\x0c\n\x05\x04\0\x02\x03\x03\x12\
    \x03\x07\x13\x14\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x08\x02\x17\n\x0c\n\
    \x05\x04\0\x02\x04\x05\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\
    \x12\x03\x08\t\x12\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x08\x15\x16\n8\
    \n\x04\x04\0\x02\x05\x12\x03\x0b\x02\x14\x1a+\"source\":\"GPS:\x20false\
    \x20Cell:false\x20Wifi:true\"\n\n\x0c\n\x05\x04\0\x02\x05\x05\x12\x03\
    \x0b\x02\x08\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\x0b\t\x0f\n\x0c\n\x05\
    \x04\0\x02\x05\x03\x12\x03\x0b\x12\x13\n\x20\n\x04\x04\0\x02\x06\x12\x03\
    \r\x02\x20\x1a\x13,\"frequency\":\"10\"}\n\n\x0c\n\x05\x04\0\x02\x06\x05\
    \x12\x03\r\x02\x07\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\r\x08\x1b\n\x0c\
    \n\x05\x04\0\x02\x06\x03\x12\x03\r\x1e\x1f\n&\n\x04\x04\0\x02\x07\x12\
    \x03\x0f\x02\x15\x1a\x19\"recording\":\"on\"\x20/\x20\"off\"\n\n\x0c\n\
    \x05\x04\0\x02\x07\x05\x12\x03\x0f\x02\x06\n\x0c\n\x05\x04\0\x02\x07\x01\
    \x12\x03\x0f\x07\x10\n\x0c\n\x05\x04\0\x02\x07\x03\x12\x03\x0f\x13\x14b\
    \x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Config::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
