// This file is generated by rust-protobuf 3.0.3. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proto/fence.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_3;

#[derive(PartialEq,Clone,Default,Debug,::serde::Serialize,::serde::Deserialize)]
// @@protoc_insertion_point(message:icecondor.Fence)
pub struct Fence {
    // message fields
    // @@protoc_insertion_point(field:icecondor.Fence.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Fence.created_at)
    pub created_at: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Fence.user_id)
    pub user_id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Fence.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Fence.geojson)
    pub geojson: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Fence.area)
    pub area: f32,
    // special fields
#[serde(skip)]
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Fence {
    fn default() -> &'a Fence {
        <Fence as ::protobuf::Message>::default_instance()
    }
}

impl Fence {
    pub fn new() -> Fence {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &Fence| { &m.id },
            |m: &mut Fence| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "created_at",
            |m: &Fence| { &m.created_at },
            |m: &mut Fence| { &mut m.created_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "user_id",
            |m: &Fence| { &m.user_id },
            |m: &mut Fence| { &mut m.user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &Fence| { &m.name },
            |m: &mut Fence| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "geojson",
            |m: &Fence| { &m.geojson },
            |m: &mut Fence| { &mut m.geojson },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "area",
            |m: &Fence| { &m.area },
            |m: &mut Fence| { &mut m.area },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Fence>(
            "Fence",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Fence {
    const NAME: &'static str = "Fence";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.id = is.read_string()?;
                },
                18 => {
                    self.created_at = is.read_string()?;
                },
                26 => {
                    self.user_id = is.read_string()?;
                },
                34 => {
                    self.name = is.read_string()?;
                },
                42 => {
                    self.geojson = is.read_string()?;
                },
                53 => {
                    self.area = is.read_float()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.created_at.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.created_at);
        }
        if !self.user_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.user_id);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.name);
        }
        if !self.geojson.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.geojson);
        }
        if self.area != 0. {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.created_at.is_empty() {
            os.write_string(2, &self.created_at)?;
        }
        if !self.user_id.is_empty() {
            os.write_string(3, &self.user_id)?;
        }
        if !self.name.is_empty() {
            os.write_string(4, &self.name)?;
        }
        if !self.geojson.is_empty() {
            os.write_string(5, &self.geojson)?;
        }
        if self.area != 0. {
            os.write_float(6, self.area)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Fence {
        Fence::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.created_at.clear();
        self.user_id.clear();
        self.name.clear();
        self.geojson.clear();
        self.area = 0.;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Fence {
        static instance: Fence = Fence {
            id: ::std::string::String::new(),
            created_at: ::std::string::String::new(),
            user_id: ::std::string::String::new(),
            name: ::std::string::String::new(),
            geojson: ::std::string::String::new(),
            area: 0.,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Fence {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Fence").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Fence {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Fence {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11proto/fence.proto\x12\ticecondor\"\x91\x01\n\x05Fence\x12\x0e\n\
    \x02id\x18\x01\x20\x01(\tR\x02id\x12\x1d\n\ncreated_at\x18\x02\x20\x01(\
    \tR\tcreatedAt\x12\x17\n\x07user_id\x18\x03\x20\x01(\tR\x06userId\x12\
    \x12\n\x04name\x18\x04\x20\x01(\tR\x04name\x12\x18\n\x07geojson\x18\x05\
    \x20\x01(\tR\x07geojson\x12\x12\n\x04area\x18\x06\x20\x01(\x02R\x04areaJ\
    \xfe\x02\n\x06\x12\x04\0\0\n\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x02\x12\x03\x01\0\x12\n\n\n\x02\x04\0\x12\x04\x03\0\n\x01\n\n\n\x03\
    \x04\0\x01\x12\x03\x03\x08\r\n\x0b\n\x04\x04\0\x02\0\x12\x03\x04\x02\x10\
    \n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x04\x02\x08\n\x0c\n\x05\x04\0\x02\0\
    \x01\x12\x03\x04\t\x0b\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x04\x0e\x0f\n\
    \x0b\n\x04\x04\0\x02\x01\x12\x03\x05\x02\x18\n\x0c\n\x05\x04\0\x02\x01\
    \x05\x12\x03\x05\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x05\t\x13\
    \n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x05\x16\x17\n\x0b\n\x04\x04\0\x02\
    \x02\x12\x03\x06\x02\x15\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x06\x02\
    \x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\x06\t\x10\n\x0c\n\x05\x04\0\
    \x02\x02\x03\x12\x03\x06\x13\x14\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x07\
    \x02\x12\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x07\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x03\x01\x12\x03\x07\t\r\n\x0c\n\x05\x04\0\x02\x03\x03\x12\x03\
    \x07\x10\x11\n\x0b\n\x04\x04\0\x02\x04\x12\x03\x08\x02\x15\n\x0c\n\x05\
    \x04\0\x02\x04\x05\x12\x03\x08\x02\x08\n\x0c\n\x05\x04\0\x02\x04\x01\x12\
    \x03\x08\t\x10\n\x0c\n\x05\x04\0\x02\x04\x03\x12\x03\x08\x13\x14\n\x0b\n\
    \x04\x04\0\x02\x05\x12\x03\t\x02\x11\n\x0c\n\x05\x04\0\x02\x05\x05\x12\
    \x03\t\x02\x07\n\x0c\n\x05\x04\0\x02\x05\x01\x12\x03\t\x08\x0c\n\x0c\n\
    \x05\x04\0\x02\x05\x03\x12\x03\t\x0f\x10b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Fence::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
