// This file is generated by rust-protobuf 3.0.3. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `proto/location.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_0_3;

#[derive(PartialEq,Clone,Default,Debug,::serde::Serialize,::serde::Deserialize)]
// @@protoc_insertion_point(message:icecondor.Location)
pub struct Location {
    // message fields
    // @@protoc_insertion_point(field:icecondor.Location.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Location.date)
    pub date: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Location.received_at)
    pub received_at: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Location.user_id)
    pub user_id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Location.device_id)
    pub device_id: ::std::string::String,
    // @@protoc_insertion_point(field:icecondor.Location.latitude)
    pub latitude: f32,
    // @@protoc_insertion_point(field:icecondor.Location.longitude)
    pub longitude: f32,
    // @@protoc_insertion_point(field:icecondor.Location.altitude)
    pub altitude: f32,
    // @@protoc_insertion_point(field:icecondor.Location.accuracy)
    pub accuracy: f32,
    // @@protoc_insertion_point(field:icecondor.Location.provider)
    pub provider: ::std::string::String,
    // special fields
#[serde(skip)]
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Location {
    fn default() -> &'a Location {
        <Location as ::protobuf::Message>::default_instance()
    }
}

impl Location {
    pub fn new() -> Location {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &Location| { &m.id },
            |m: &mut Location| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "date",
            |m: &Location| { &m.date },
            |m: &mut Location| { &mut m.date },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "received_at",
            |m: &Location| { &m.received_at },
            |m: &mut Location| { &mut m.received_at },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "user_id",
            |m: &Location| { &m.user_id },
            |m: &mut Location| { &mut m.user_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "device_id",
            |m: &Location| { &m.device_id },
            |m: &mut Location| { &mut m.device_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "latitude",
            |m: &Location| { &m.latitude },
            |m: &mut Location| { &mut m.latitude },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "longitude",
            |m: &Location| { &m.longitude },
            |m: &mut Location| { &mut m.longitude },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "altitude",
            |m: &Location| { &m.altitude },
            |m: &mut Location| { &mut m.altitude },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "accuracy",
            |m: &Location| { &m.accuracy },
            |m: &mut Location| { &mut m.accuracy },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "provider",
            |m: &Location| { &m.provider },
            |m: &mut Location| { &mut m.provider },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Location>(
            "Location",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Location {
    const NAME: &'static str = "Location";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.id = is.read_string()?;
                },
                18 => {
                    self.date = is.read_string()?;
                },
                26 => {
                    self.received_at = is.read_string()?;
                },
                34 => {
                    self.user_id = is.read_string()?;
                },
                42 => {
                    self.device_id = is.read_string()?;
                },
                53 => {
                    self.latitude = is.read_float()?;
                },
                61 => {
                    self.longitude = is.read_float()?;
                },
                69 => {
                    self.altitude = is.read_float()?;
                },
                77 => {
                    self.accuracy = is.read_float()?;
                },
                82 => {
                    self.provider = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if !self.date.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.date);
        }
        if !self.received_at.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.received_at);
        }
        if !self.user_id.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.user_id);
        }
        if !self.device_id.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.device_id);
        }
        if self.latitude != 0. {
            my_size += 1 + 4;
        }
        if self.longitude != 0. {
            my_size += 1 + 4;
        }
        if self.altitude != 0. {
            my_size += 1 + 4;
        }
        if self.accuracy != 0. {
            my_size += 1 + 4;
        }
        if !self.provider.is_empty() {
            my_size += ::protobuf::rt::string_size(10, &self.provider);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if !self.date.is_empty() {
            os.write_string(2, &self.date)?;
        }
        if !self.received_at.is_empty() {
            os.write_string(3, &self.received_at)?;
        }
        if !self.user_id.is_empty() {
            os.write_string(4, &self.user_id)?;
        }
        if !self.device_id.is_empty() {
            os.write_string(5, &self.device_id)?;
        }
        if self.latitude != 0. {
            os.write_float(6, self.latitude)?;
        }
        if self.longitude != 0. {
            os.write_float(7, self.longitude)?;
        }
        if self.altitude != 0. {
            os.write_float(8, self.altitude)?;
        }
        if self.accuracy != 0. {
            os.write_float(9, self.accuracy)?;
        }
        if !self.provider.is_empty() {
            os.write_string(10, &self.provider)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Location {
        Location::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.date.clear();
        self.received_at.clear();
        self.user_id.clear();
        self.device_id.clear();
        self.latitude = 0.;
        self.longitude = 0.;
        self.altitude = 0.;
        self.accuracy = 0.;
        self.provider.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Location {
        static instance: Location = Location {
            id: ::std::string::String::new(),
            date: ::std::string::String::new(),
            received_at: ::std::string::String::new(),
            user_id: ::std::string::String::new(),
            device_id: ::std::string::String::new(),
            latitude: 0.,
            longitude: 0.,
            altitude: 0.,
            accuracy: 0.,
            provider: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Location {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Location").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Location {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Location {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14proto/location.proto\x12\ticecondor\"\x93\x02\n\x08Location\x12\
    \x0e\n\x02id\x18\x01\x20\x01(\tR\x02id\x12\x12\n\x04date\x18\x02\x20\x01\
    (\tR\x04date\x12\x1f\n\x0breceived_at\x18\x03\x20\x01(\tR\nreceivedAt\
    \x12\x17\n\x07user_id\x18\x04\x20\x01(\tR\x06userId\x12\x1b\n\tdevice_id\
    \x18\x05\x20\x01(\tR\x08deviceId\x12\x1a\n\x08latitude\x18\x06\x20\x01(\
    \x02R\x08latitude\x12\x1c\n\tlongitude\x18\x07\x20\x01(\x02R\tlongitude\
    \x12\x1a\n\x08altitude\x18\x08\x20\x01(\x02R\x08altitude\x12\x1a\n\x08ac\
    curacy\x18\t\x20\x01(\x02R\x08accuracy\x12\x1a\n\x08provider\x18\n\x20\
    \x01(\tR\x08providerJ\xda\x04\n\x06\x12\x04\0\0\x0f\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x01\0\x12\n\n\n\x02\x04\0\x12\
    \x04\x03\0\x0f\x01\n\n\n\x03\x04\0\x01\x12\x03\x03\x08\x10\n\x0b\n\x04\
    \x04\0\x02\0\x12\x03\x04\x02\x11\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x04\
    \x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x04\t\x0b\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\x04\x0e\x0f\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x05\x02\
    \x12\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x05\x02\x08\n\x0c\n\x05\x04\0\
    \x02\x01\x01\x12\x03\x05\t\r\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x05\
    \x10\x11\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x06\x02\x19\n\x0c\n\x05\x04\0\
    \x02\x02\x05\x12\x03\x06\x02\x08\n\x0c\n\x05\x04\0\x02\x02\x01\x12\x03\
    \x06\t\x14\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x06\x17\x18\n\x0b\n\x04\
    \x04\0\x02\x03\x12\x03\x07\x02\x15\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\
    \x07\x02\x08\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x07\t\x10\n\x0c\n\x05\
    \x04\0\x02\x03\x03\x12\x03\x07\x13\x14\n\x0b\n\x04\x04\0\x02\x04\x12\x03\
    \x08\x02\x17\n\x0c\n\x05\x04\0\x02\x04\x05\x12\x03\x08\x02\x08\n\x0c\n\
    \x05\x04\0\x02\x04\x01\x12\x03\x08\t\x12\n\x0c\n\x05\x04\0\x02\x04\x03\
    \x12\x03\x08\x15\x16\n\x0b\n\x04\x04\0\x02\x05\x12\x03\n\x02\x15\n\x0c\n\
    \x05\x04\0\x02\x05\x05\x12\x03\n\x02\x07\n\x0c\n\x05\x04\0\x02\x05\x01\
    \x12\x03\n\x08\x10\n\x0c\n\x05\x04\0\x02\x05\x03\x12\x03\n\x13\x14\n\x0b\
    \n\x04\x04\0\x02\x06\x12\x03\x0b\x02\x16\n\x0c\n\x05\x04\0\x02\x06\x05\
    \x12\x03\x0b\x02\x07\n\x0c\n\x05\x04\0\x02\x06\x01\x12\x03\x0b\x08\x11\n\
    \x0c\n\x05\x04\0\x02\x06\x03\x12\x03\x0b\x14\x15\n\x0b\n\x04\x04\0\x02\
    \x07\x12\x03\x0c\x02\x15\n\x0c\n\x05\x04\0\x02\x07\x05\x12\x03\x0c\x02\
    \x07\n\x0c\n\x05\x04\0\x02\x07\x01\x12\x03\x0c\x08\x10\n\x0c\n\x05\x04\0\
    \x02\x07\x03\x12\x03\x0c\x13\x14\n\x0b\n\x04\x04\0\x02\x08\x12\x03\r\x02\
    \x15\n\x0c\n\x05\x04\0\x02\x08\x05\x12\x03\r\x02\x07\n\x0c\n\x05\x04\0\
    \x02\x08\x01\x12\x03\r\x08\x10\n\x0c\n\x05\x04\0\x02\x08\x03\x12\x03\r\
    \x13\x14\n\x0b\n\x04\x04\0\x02\t\x12\x03\x0e\x02\x17\n\x0c\n\x05\x04\0\
    \x02\t\x05\x12\x03\x0e\x02\x08\n\x0c\n\x05\x04\0\x02\t\x01\x12\x03\x0e\t\
    \x11\n\x0c\n\x05\x04\0\x02\t\x03\x12\x03\x0e\x14\x16b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(Location::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
